### ISSUE TITLE
descriptors - date not in english

### ISSUE THREAD

**Issue by anoop-rc** [chenquincy/vue-dynamic-form-component#1]
How do I render the date format in english?

**Comment by chenquincy** [comment]
@anoop-rc I'm sorry that it's not supported now. I will fix this soon.

**Comment by chenquincy** [comment]
@anoop-rc  The v2.0.0 has been published. You ca use it now. Refer to: [vue-dynamic-form-component i18n](https://vue-dynamic-form.quincychen.cn/i18n/)
