### ISSUE TITLE
貌似没法扩展增加自定义组件

### ISSUE THREAD

**Issue by StickChen** [chenquincy/vue-dynamic-form-component#12]
支持嵌套、数组、Map很好，不过貌似没法扩展增加自定义组件？

**Comment by chenquincy** [comment]
@StickChen  
不好意思，之前忘记回复了，由于是基于数据类型的表单，所以一开始只是实现了常用数据的表单组件，并没有考虑支持自定义组件。
不过目前来看似乎支持这个功能会更好，类似上传文件等复杂需求是需要这个功能的，想法已经有了，但是最近事情太多没时间去实现，后续有时间会更新的~

**Comment by chenquincy** [comment]
@StickChen 自定义组件功能已实现，可以查看文档了解用法

**Comment by odayou** [comment]
> @StickChen 自定义组件功能已实现，可以查看文档了解用法

hi，你的组件很好用，点赞。不过请问自定义组件怎么拿到预设的数据进行反显，以及怎么把组件设置的数据朝外同步数据。

**Comment by chenquincy** [comment]
@odayou  数据变更向外同步可以利用给自定义组件添加 input 事件的方式，不管是通过 vuex 还是消息广播都行
