### ISSUE TITLE
 enum   multiple: true,  校验不通过

### ISSUE THREAD

**Issue by chris-js** [chenquincy/vue-dynamic-form-component#14]
我看input.vue 里面 select框 有做:multiple="descriptor.multiple"   但是设置了值之后 校验都不能通过，还需要设置什么吗

**Comment by chenquincy** [comment]
@jscaden  可以的话提供一下 descriptors

**Comment by jscaden** [comment]
descriptors 👍: {
      enum: {
        type: 'enum',
        label: '下拉框',
        enum: ['value1', 'value2'],
        multiple: true,
        options: [
          { label: '选项1', value: 'value1' },
          { label: '选项2', value: 'value2' }
        ]
      },
}

**Comment by chenquincy** [comment]
@jscaden  可以看看文档这里：[多选数组](https://vue-dynamic-form.quincychen.cn/zh/getting-started/#%E6%95%B0%E7%BB%84)，应该设置成 `type: 'array'`，`defaultField.type`再设置成 `enum`
