### ISSUE TITLE
validator 字段间联动

### ISSUE THREAD

**Issue by odayou** [chenquincy/vue-dynamic-form-component#16]
hi，
在表单校验中，很常见的一个场景是，需要字段之间互相验证，但是貌似现在回调中没法拿到form对象。
demo（请看我注释部分）:
```javascript
url: [
    {
      type: 'url',
      label: '图片地址',
      message: '必须输入网址类型的内容',
      placeholder: 'http(s)://'
    },
    {
      message: '图片地址必填',
      validator: (rule, value, callback) => {
          // 这里我想在判定path字段有值的时候让校验通过， 没有path的时候提示此字段必填
          // 这里怎么获取form对象，进而获取path的内容？
          callback()// 自定义校验， 出错调用callback(new Error('错误信息'))， 校验通过：callback()
      }
    }
],
path: {
    type: 'string',
    label: '上传图片',
    required: true,
    message: '不能为空'
}
```

**Comment by chenquincy** [comment]
@odayou  你可以在 created 中设置 descriptors，同时配置
``` vue
<dynamic-form v-mode="data" v-if="descriptors"></dynamic-form>
```
在 created 中你可以在 validator 中通过 `this.data.path` 判断当前值是否为空

**Comment by odayou** [comment]
> @odayou 你可以在 created 中设置 descriptors，同时配置
> 
> ```
> <dynamic-form v-model="data" v-if="descriptors"></dynamic-form>
> ```
> 
> 在 created 中你可以在 validator 中通过 `this.data.path` 判断当前值是否为空

好的， 我明白你的意思。 如果是单一作用的组件可以这么做，但是我的场景略不一样：data、descriptors都是外部传进来再传给dynamic-form组件，dynamic-form所在的组件不能写死任何代码，我再想想别的办法，再次谢谢你的回复
