### ISSUE TITLE
联动控件控制

### ISSUE THREAD

**Issue by lucasguo** [chenquincy/vue-dynamic-form-component#17]
联动控件的显示和校验怎么做呢，有没有例子？
比如有下拉框1、输入框1、输入框2
下拉框1值选择1时，输入框1显示并必填，输入框2隐藏
下拉框1值选择2时，输入框2显示并必填，输入框1隐藏

**Comment by chenquincy** [comment]
@lucasguo  抱歉回复慢了，目前表单组件对联动的原生支持较弱，
1. 需要通过 $set 重写 descriptors 触发表单重新绘制。
2. 通过自定义组件的方式，文档中有关于自定义组件的使用。
