### ISSUE TITLE
自定义组件如何做到数据回显？

### ISSUE THREAD

**Issue by mbt522533623** [chenquincy/vue-dynamic-form-component#18]

**Comment by mbt522533623** [comment]
<template>
  <div>
    
    <dynamic-form class="my-dy-form" v-model="data" :descriptors="descriptors"></dynamic-form>
  </div>
</template>
<script>
export default {
  data() {
    return {
      descriptors: {
        advList: {
          type: "array",
          label: "广告列表",
          defaultField: {
            type: "object",
            fields: {
              advNo: { label: "广告编号", type: "string" },
              advName: { label: "广告名称", type: "string" },
              advState: { label: "状态", type: "string" },
              advImg: {
                label: "广告图片",
                type: "url",
                component: {
                  name: "el-image",
                  props: ["src"]
                }
              },
              createDate: { label: "创建时间", type: "date" }
            }
          }
        }
      },
      data: {
        advList: [
          {
            advNo: "1",
            advName: "测试广告",
            advState: "启用",
            createDate: "2020-05-02 18:22:18",
            advImg:"https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1906469856,4113625838&fm=26&gp=0.jpg"
         
          },
          {
            advNo: "2",
            advName: "测试广告2",
            advState: "启用",
            createDate: "2020-05-02 18:22:18"
          },
          {
            advNo: "3",
            advName: "测试广告3",
            advState: "禁用",
            createDate: "2020-05-02 18:22:18"
          }
        ]
      },
      form: {},
      option: {
        card: true,
        menuBtn: false,
        group: [
          {
            icon: "el-icon-info",
            label: "分组1",
            prop: "group1",
            column: [
              {
                label: "测试",
                prop: "text1",
                span: 8,
                prop: "group5"
              },
              {
                label: "测试",
                prop: "img",
                span: 8,
                type: "img"
              }
            ]
          },
          {
            icon: "el-icon-info",
            label: "分组2",
            prop: "group2",
            column: [
              {
                label: "选项卡2",
                prop: "text2",
                span: 8
              },
              {
                label: "选项卡3",
                prop: "text3",
                span: 8
              },
              {
                label: "选项卡4 ",
                prop: "text3",
                span: 8,
                column: [
                  {
                    label: "内容",
                    prop: "text"
                  }
                ]
              }
            ]
          },
          {
            icon: "el-icon-info",
            label: "分组2",
            prop: "group3",
            column: [
              {
                label: "选项卡2",
                prop: "text2",
                span: 8
              },
              {
                label: "选项卡3",
                prop: "text3",
                span: 8
              },
              {
                label: "选项卡4 ",
                prop: "text3",
                span: 8,
                column: [
                  {
                    label: "内容",
                    prop: "text"
                  }
                ]
              }
            ]
          },
          {
            icon: "el-icon-info",
            label: "分组2",
            prop: "group4",
            column: [
              {
                label: "选项卡2",
                prop: "text2",
                span: 8
              },
              {
                label: "选项卡3",
                prop: "text3",
                span: 8
              },
              {
                label: "选项卡4 ",
                prop: "text3",
                span: 8
              }
            ]
          }
        ]
      }
    };
  }
};
</script>

<style lang="scss">
// .my-dy-form .el-icon-close {
//   display: none;
// }

// .my-dy-form .el-button--primary.is-plain {
//   display: none;
// }
</style>

**Comment by mbt522533623** [comment]
descriptors: {
        advList: {
          type: "array",
          label: "广告列表",
          defaultField: {
            type: "object",
            fields: {
              advNo: { label: "广告编号", type: "string" },
              advName: { label: "广告名称", type: "string" },
              advState: { label: "状态", type: "string" },
              advImg: {
                label: "广告图片",
                type: "url",
                component: {
                  name: "el-image",
                  props: ["src"]
                }
              },
              createDate: { label: "创建时间", type: "date" }
            }
          }
        }
      },
      data: {
        advList: [
          {
            advNo: "1",
            advName: "测试广告",
            advState: "启用",
            createDate: "2020-05-02 18:22:18",
            advImg:"https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1906469856,4113625838&fm=26&gp=0.jpg"
         
          },
          {
            advNo: "2",
            advName: "测试广告2",
            advState: "启用",
            createDate: "2020-05-02 18:22:18"
          },
          {
            advNo: "3",
            advName: "测试广告3",
            advState: "禁用",
            createDate: "2020-05-02 18:22:18"
          }
        ]
      },

**Comment by mbt522533623** [comment]
动态数据如何回显图片到自定义组件里面

**Comment by chenquincy** [comment]
@mbt522533623 由于组件是通过 v-model 绑定数据的，因此你需要基于 el-image 封装一个自定义组件，假设组件名称为 `CustomImage.vue`。
``` vue
<template>
  <div class="custom-image">
    <el-image :src="_value"></el-image>
  </div>
</template>

<script>
export default {
  name: 'custom-image',
  props: {
    value: {
      required: true
    }
  },
  computed: {
    _value: {
      get () {
        return this.value
      },
      set (value) {
        this.$emit('input', value)
      }
    }
  }
}
</script>
```
之后需要在全局注册这个组件，在你的 main.js 中
``` js
import CustomImage from './CustomImage'
Vue.component(CustomImage.name, CustomImage)
```
然后 descriptors 中将自定义组件的name 从 `el-image` 改为 `custom-image` 即可

**Comment by chenquincy** [comment]
当然，你也可以在这个组件内封装更多的自定义逻辑

**Comment by chenquincy** [comment]
@mbt522533623  我已经在文档[自定义组件](https://vue-dynamic-form.quincychen.cn/zh/getting-started/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6)中添加了更多示例，感谢反馈
