### ISSUE TITLE
Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by paolog22** [chenquincy/vue-dynamic-form-component#19]
![image](https://user-images.githubusercontent.com/12680745/82121677-72479e80-97c1-11ea-958f-6a06bed1db3a.png)
`id: { type: 'string', label: 'ID', required: false },
    vin: { type: 'string', label: 'VIN', required: false },
    licence_number: { type: 'string', label: 'Licence Number', required: false },
    test: {
        type: 'object',
        label: 'Normal Object',
        fields: {
            object: {
                type: 'object',
                label: 'Child Object',
                fields: {
                    boolean: { type: 'boolean', required: true },
                    number: { type: 'number', required: true },
                    string: { type: 'string', required: true, pattern: /^test$/g }
                }
            },
            boolean: { type: 'boolean', required: true },
            number: { type: 'number', required: true },
            string: { type: 'string', required: true, pattern: /^test$/g }
        }
    }`

it perfectly render the first 3 item but when creating and object it says 

> Cannot read property 'object' of undefined

what am i missing ?

**Comment by chenquincy** [comment]
@paolog22 I had tried your descriptors but without any error. Did you set an initial data？
![image](https://user-images.githubusercontent.com/10976378/82147754-7b4c7480-9882-11ea-882b-1cd4a5cb607d.png)

**Comment by paolog22** [comment]
what do you mean by initial data? @chenquincy

**Comment by chenquincy** [comment]
@paolog22 Could you give a demo in [codepen](https://codepen.io/) to me?

**Comment by paolog22** [comment]
@chenquincy sorry i forgot to include the exact code here is the screenshot
![image](https://user-images.githubusercontent.com/12680745/82283390-d5efe880-99c8-11ea-9cd5-8a0d24b9d842.png)

**Comment by chenquincy** [comment]
@paolog22  How did you imported the dynamic-form component? NPM or script element? And, which version did you used?

**Comment by paolog22** [comment]
@chenquincy 
![image](https://user-images.githubusercontent.com/12680745/82347715-8d691700-9a2a-11ea-82a0-779ce1ff673e.png)

"element-ui": "^2.13.1"
 "vue-dynamic-form-component": "^2.5.0"

**Comment by chenquincy** [comment]
@paolog22  When you set the descriptors of DynamicForm? It look like you didn't set the descriptors(in your demo is `schema`) before the DynamicForm render.
The descriptors should be set before the DynamicForm render, you can set it in `created` method. Add `v-if="schema"` to DynamicForm(make sure descriptors is set before render), if you want to add descriptors after some methods.

**Comment by paolog22** [comment]
@chenquincy thanks will try to add default scheme while fetching the real one. will get back to you soon :)

**Comment by paolog22** [comment]
![image](https://user-images.githubusercontent.com/12680745/82409949-70bbf600-9aa1-11ea-9fe8-daa28fe05d76.png)
still the same @chenquincy

**Comment by chenquincy** [comment]
@paolog22  Set the default scheme can't resolve this issue, because the real scheme still set after the component render. You should use `v-if` to set it like this:
``` vue
<template>
  <div id="app">
    <dynamic-form v-if="schema" v-model="data" lang="en_US" :descriptors="schema"></dynamic-form>
  </div>
</template>

<script>
import FormService from 'your-form-service'
import defaultForm from 'your-default-form'

export default {
  name: 'App',
  components: {},
  data () {
    return {
      data: {},
      schema: null
    }
  },
  created () {
    FormService.fetchByType('id', 'type').then(res => {
      this.schema = res.form
    }).catch(e => {
      this.schema = defaultForm
    })
  }
}
</script>
```
Set the inital schema to `null` with `v-if="schema"` could promise that component render after the real schema be set.

**Comment by paolog22** [comment]
i see.. will do this thanks @chenquincy you're very active and responsive .

**Comment by chenquincy** [comment]
@paolog22 Thanks for your appreciation. Close the issue please if it work. Feel free to ask more questions.

**Comment by paolog22** [comment]
thanks got it now :) closing this issue
