### ISSUE TITLE
how to make multi select with object value ?

### ISSUE THREAD

**Issue by paolog22** [chenquincy/vue-dynamic-form-component#20]
hi @chenquincy 
how to make multi select with object value ?
i am having this error 

![image](https://user-images.githubusercontent.com/12680745/82567977-b87d7300-9bb0-11ea-9980-e1223d6954d7.png)

here is my code 
``` javascript
equipments: {
        type: 'object',
        label: 'Equipments',
        fields: {
            equipment: {
                type: 'enum',
                required: false,
                multiple: true,
                enum: equipments,
                options: equipments.map((i, index) => {
                    return {
                        label: i.text,
                        value: i,
                        key: index
                    }
                })
            }
        }
    }
```

the _equipments_ is an array of object like  `[ { text: 'option 1' } ]`

and i want to make the _equipment_ key as an array of object as a value

**Comment by chenquincy** [comment]
@paolog22 Have you saw [this part](https://vue-dynamic-form.quincychen.cn/getting-started/#array) of docs? It will teach you how to use mutli-select. Note that `Object` isn't enumerable, so you can map data to `String` with `JSON.stringify` in form, don't forget to `JSON.parse` the data before submit. Here is the demo:
``` javascript
let equipments = [
  { text: 'option-1' },
  { text: 'option-2' },
  { text: 'option-3' }
]
equipments = equipments.map(i => JSON.stringify(i))

const descriptors = {
  equipments: {
    type: 'object',
    label: 'Equipments',
    fields: {
      equipment: {
        type: 'array',
        required: false,
        defaultField: {
          type: 'enum',
          multiple: true,
          enum: equipments,
          options: equipments.map((i, index) => {
            return {
              label: JSON.parse(i).text,
              value: i,
              key: index
            }
          })
        }
      }
    }
  }
}
```

**Comment by paolog22** [comment]
@chenquincy i did saw that part of docs. but that stringify thing i got confused. thanks

**Comment by chenquincy** [comment]
@paolog22 `Object` value is not enumerable, so it's not a good choice to use object values in multi-select. Use `stringify` change object to string can make the values enumerable. Another way is use options like `['option-1', 'option-2']` in form and convert them to object before submit.
Any confusion else?

**Comment by paolog22** [comment]
@chenquincy  thanks you will close this now.
