### ISSUE TITLE
自定义组件返回参数校验问题

### ISSUE THREAD

**Issue by tianzhu1992** [chenquincy/vue-dynamic-form-component#28]
你好作者，当我使用自定义组件去实现一个表单时，如果自定义组件返回值类型为Array或者Object时，例如级联选择，我这边该如何处理返回值与type不对应的问题
![image](https://user-images.githubusercontent.com/31034218/92220695-f045c780-eece-11ea-9c7c-757985f2bd1f.png)

![image](https://user-images.githubusercontent.com/31034218/92221152-9eea0800-eecf-11ea-9386-5e06461bde81.png)

![image](https://user-images.githubusercontent.com/31034218/92221002-60544d80-eecf-11ea-9da8-52cc58f81fd0.png)

**Comment by szymonsterczewski** [comment]
@tianzhu1992 did you solve it?

**Comment by chenquincy** [comment]
@tianzhu1992  不好意思，忘记处理问题了，el-cascader 获取的数据类型是 array，旧版本不支持 Object 或者 Array 的自定义组件，[2.7.0](https://github.com/chenquincy/vue-dynamic-form-component/releases/tag/v2.7.0) 版本已支持，你把例子中 fruit 的 type 改为 `array` 即可

**Comment by chenquincy** [comment]
> @tianzhu1992 did you solve it?

Try [0.2.7](https://github.com/chenquincy/vue-dynamic-form-component/releases/tag/v2.7.0), change fruit's type from `string` to `array` can solve this issue.

**Comment by szymonsterczewski** [comment]
@chenquincy what about 'string' field with custom **el-date**?

**Comment by tianzhu1992** [comment]
@chenquincy According to your ideas, I have written a new one myself. Thank you for your ideas

**Comment by chenquincy** [comment]
> @chenquincy According to your ideas, I have written a new one myself. Thank you for your ideas

@tianzhu1992  sorry for late.

**Comment by chenquincy** [comment]
> @chenquincy what about 'string' field with custom **el-date**?

@szymonsterczewski  Change 'string' to 'date' will work.(ps: there is no `el-date`, maybe you means `el-date-picker`)

**Comment by szymonsterczewski** [comment]
@chenquincy Thanks for answer, I tried this way, but I need format 2020-09-01 (yyyy-MM-dd) without time, and it doesnt work... There is the same problem as in case of @tianzhu1992

**Comment by chenquincy** [comment]
> @chenquincy Thanks for answer, I tried this way, but I need format 2020-09-01 (yyyy-MM-dd) without time. There is the same problem as in case of @tianzhu1992

@szymonsterczewski  I have tried your case.
``` js
const descriptors = {
  date: {
    type: 'date',
    message: '请选择日期',
    required: true,
    component: {
      name: 'el-date-picker',
      props: {
        format: 'yyyy-MM-dd'
      }
    }
  }
}
```
This `descriptors` work well.

**Comment by chenquincy** [comment]
@szymonsterczewski This issue will be closed later without other questions.

**Comment by szymonsterczewski** [comment]
@chenquincy I am trying to build backend dynamic forms which will be rendered by your component.

**First version:**
`public $type = 'string';
    public $component = [
        "name" => 'el-date-picker',
        "type" => 'date',
        "format" => "yyyy-MM-dd",
    ];`

You are right. My mistake is in nested component, it should be:

**Fixed version**
`public $type = 'string';
    public $component = [
        "name" => 'el-date-picker',
        "type" => 'date',
        "props" => [
            "format" => "yyyy-MM-dd",
        ],
    ];`

Thank you very much.

**Comment by szymonsterczewski** [comment]
@chenquincy Oh! this is my real problem, it is causing this error. Even if it's displayed properly.

<img width="524" alt="Zrzut ekranu 2020-09-16 o 09 35 24" src="https://user-images.githubusercontent.com/22393538/93306306-f6f20a00-f7ff-11ea-97fa-4be90ad9d6cd.png">

**Comment by chenquincy** [comment]
> @chenquincy Oh! this is my real problem, it is causing this error. Even if it's displayed properly.
> 
> <img alt="Zrzut ekranu 2020-09-16 o 09 35 24" width="524" src="https://user-images.githubusercontent.com/22393538/93306306-f6f20a00-f7ff-11ea-97fa-4be90ad9d6cd.png">

You should add `value-format` prop, if you want to get a string value.

**Comment by chenquincy** [comment]
> > @chenquincy Thanks for answer, I tried this way, but I need format 2020-09-01 (yyyy-MM-dd) without time. There is the same problem as in case of @tianzhu1992
> 
> @szymonsterczewski I have tried your case.
> 
> ```js
> const descriptors = {
>   date: {
>     type: 'date',
>     message: 'please choose the date',
>     required: true,
>     component: {
>       name: 'el-date-picker',
>       props: {
>         format: 'yyyy-MM-dd',
>         'value-format': 'yyyy-MM-dd'
>       }
>     }
>   }
> }
> ```
> 
> This `descriptors` work well.

@szymonsterczewski  Add value-format prop, if you want to get a string value.

**Comment by szymonsterczewski** [comment]
Works, thank you again.
