### ISSUE TITLE
[question] how to disable input by switch

### ISSUE THREAD

**Issue by NoneGG** [chenquincy/vue-dynamic-form-component#30]
### what i want
I want to disable the form when i press one button, incase of form content being changed any more.
Usually i can do this by set `:disable="true"`(may be by a switch)

###  problem
I find no related config in docs, how can i do this?

Thanks a lot, looking forward for your reply~

**Comment by chenquincy** [comment]
@NoneGG  Thanks for your issue, it's a good feature. The current version can meet your need but not convenient. I will give a better solution later.

**Comment by chenquincy** [comment]
@NoneGG `2.8.0` version has been published. `dynamic-form` now has a `disabled` prop. You can use it like:
``` vue
<template>
    <dynamic-form
      v-model="data"
      lang="en_US"
      :descriptors="descriptors"
      :disabled="disabled" />
</template>
```

**Comment by NoneGG** [comment]
@chenquincy Thanks a lot~
