### ISSUE TITLE
Custom Component only support type 'string' but not show correctly when type is 'number'

### ISSUE THREAD

**Issue by zhixiao-kooboo** [chenquincy/vue-dynamic-form-component#33]
Hi @chenquincy 
I want to use Custom Component(el-input-number) with type 'number', it's not shows `el-input-number` but `el-input`. 
When I change the type into 'string', the `el-input-number` shows
```
 this.descriptors[item.FieldName] = {
            type: 'number',
            label: 'number',
            required: false,
            component: {
              name: 'el-input-number',
            },
          }
```

I want to use `el-input-number` instead of `el-input` with `.Number` because we can not input float and int at both if the type is number

**Comment by chenquincy** [comment]
@zhixiao-kooboo It's a bug obviously and has been fixed at `2.8.1` version. Thx your report.

**Comment by chenquincy** [comment]
You don't need to use `component.name` again, type `number` will use `el-input-number` default.

**Comment by zhixiao-kooboo** [comment]
Thanks for the suggestion
