### ISSUE TITLE
自定义组件 el-radio-group >>> el-radio-button 存在 Vue 组件未注册的警告！

### ISSUE THREAD

**Issue by wangyesheng** [chenquincy/vue-dynamic-form-component#49]
好兄弟，你好，自定义组件 el-radio-group >>> el-radio-button 存在 Vue 组件未注册的警告！详情见下图，版本 2.8.1。
![image](https://user-images.githubusercontent.com/42696348/129302459-96d2068a-3900-46ee-969b-0584b7286a02.png)
![image](https://user-images.githubusercontent.com/42696348/129302662-ff2c2ba2-2a99-4e4f-be33-a0ae836f4c7c.png)

**Comment by chenquincy** [comment]
@wangyesheng element-ui 的相关组件需要自行注册，参考 [全局注册](https://vue-dynamic-form.quincychen.cn/zh/getting-started/#%E5%85%A8%E5%B1%80%E6%B3%A8%E5%86%8C)。这里是注册了所有的 element-ui，也可以参考 element-ui 文档部分注册。

**Comment by wangyesheng** [comment]
@chenquincy 已经全局注册过了，大佬
![image](https://user-images.githubusercontent.com/42696348/129319320-0503dfb0-0696-4a4a-a8fb-8fa31537a4ff.png)

**Comment by chenquincy** [comment]
@wangyesheng 看了下是 element-ui 的问题，el-radio-group 没有 name 属性。你可以去 element-ui 那里提 issue，或者忽略，warning 不影响使用。

**Comment by wangyesheng** [comment]
@chenquincy 嗯嗯，好的，再请教一个问题，我想自定义单选框组件，比如我的性别选项渲染的是男和女，但是取值的时候我想取得 1 或 0，有没有什么属性可以支持，渲染为中文，值为数字。
![image](https://user-images.githubusercontent.com/42696348/129327528-ed349582-1e96-4f72-bb21-9f5fc7a4ac44.png)
![image](https://user-images.githubusercontent.com/42696348/129326936-1b479974-ce2d-4139-a16e-315fbb640be4.png)
![image](https://user-images.githubusercontent.com/42696348/129327025-37825454-7a60-4834-8931-e563a60f63bf.png)

**Comment by chenquincy** [comment]
@wangyesheng 自定义组件的 children 可以直接为 string，也就是你想要显示的内容，label 属性是 value。
``` js
{
    type: 'string',
    component: {
      name: 'el-radio',
      props: {
        label: 'test' // value
      },
      children: '测试' // 显示内容
  }
}
```

**Comment by wangyesheng** [comment]
@chenquincy 好兄弟，你太棒了，太感谢了，是判断传入的 children 类型进行绑定 label 或者渲染为子 vnode 的吗？

**Comment by wangyesheng** [comment]
@chenquincy 上一个注册的问题也解决了 升级下 element 版本就行

**Comment by chenquincy** [comment]
> @wangyesheng 自定义组件的 children 可以直接为 string，也就是你想要显示的内容，label 属性是 value。
> 
> ```js
> {
>       name: 'el-radio',
>       props: {
>         label: 'test' // value
>       },
>       children: '测试' // 显示内容
> }
> ```

这个配置会被解析成 `<el-radio label="test">测试</el-radio>`

**Comment by wangyesheng** [comment]
> > @wangyesheng 自定义组件的 children 可以直接为 string，也就是你想要显示的内容，label 属性是 value。
> > ```js
> > {
> >       name: 'el-radio',
> >       props: {
> >         label: 'test' // value
> >       },
> >       children: '测试' // 显示内容
> > }
> > ```
> 
> 这个配置会被解析成 `<el-radio label="test">测试</el-radio>`

嗯嗯，解决了，谢谢好兄弟
