### ISSUE TITLE
表单组件input是否可以支持upload文件上传呢？

### ISSUE THREAD

**Issue by wenxiayili** [chenquincy/vue-dynamic-form-component#5]
功能：支持文件上传（一般表单是图片）
其中很重要的功能点：上传成功后回调函数，可以自定义回调函数，用来自定义处理逻辑。

**Comment by chenquincy** [comment]
@wenxiayili  这个有考虑要支持，还在构思中，可能会以自定义组件的方式支持，具体完成时间还不清楚

**Comment by wenxiayili** [comment]
今后几天我会研究下这个功能，随时交流，感谢！

**Comment by wenxiayili** [comment]
@chenquincy 今后几天我会研究下这个功能，随时交流，感谢！

**Comment by chenquincy** [comment]
@wenxiayili  有好的想法欢迎PR~

**Comment by jscaden** [comment]
这个功能研究的如何，请教一下如何实现

**Comment by chenquincy** [comment]
@jscaden 
大概思路已经有了，但是没什么时间去实现，我看看这周末能不能抽出时间做一下 -。-
目前已经实现了组件 props 的自定义，再实现组件名和绑定事件的自定义，就可以根据 [element.upload组件文档](https://element.faas.ele.me/#/zh-CN/component/upload) 自定义相关组件

**Comment by jscaden** [comment]
我直接在form.vue文件里面 做type==‘upload’  判断
<div  v-for="(descriptor, key) in descriptors">
        <el-form-item  v-if="descriptor.type=='upload'" :label="descriptor.label"  class="dynamic-form-item" labelWidth="156px" >
            <el-upload
            class="upload-demo"
            :headers="Authorization"
            action=""
            :on-success="onChangePreview"
            drag
            multiple
            :limit="1"
            >
            <i class="el-icon-upload"></i>
            <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
          </el-upload>
        </el-form-item>
      <dynamic-form-item
        v-else
        v-model="_value[key]"
        :key="key"
        :lang="lang"
        :label="findTypeDescriptor(descriptor).label || key"
        :prop="key"
        :label-width="labelWidth"
        :descriptor="descriptor"
        :language="language"
        :size="size"
        :background-color="backgroundColor"
        :bg-color-offset="bgColorOffset">
      </dynamic-form-item>

      </div>

**Comment by chenquincy** [comment]
@wenxiayili  @jscaden  不好意思鸽了这么久 -。-
这个功能已经实现了。你们可以使用 2.5.0 版本试试看，文档在这：[自定义组件](https://vue-dynamic-form.quincychen.cn/zh/getting-started/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6)
