### ISSUE TITLE
自定义样式可以吗，现在每个input框各自一行

### ISSUE THREAD

**Issue by chengxiaozhu** [chenquincy/vue-dynamic-form-component#50]

**Comment by ruofee** [comment]
https://vue-dynamic-form.quincychen.cn/zh/getting-started/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6

**Comment by ruofee** [comment]
> https://vue-dynamic-form.quincychen.cn/zh/getting-started/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6

自定义组件应该可以满足你的需求

**Comment by chenquincy** [comment]
无响应
