### ISSUE TITLE
如何在descriptors中设置表单的属性

### ISSUE THREAD

**Issue by OhBonsai** [chenquincy/vue-dynamic-form-component#6]
Hi，  谢谢你做了这么棒的组件。

我想要一个多行的input, descriptors是否支持？
<el-input>增加一下attr就行了
```
    "type": 'textarea',
    "rows": 3
```

**Comment by chenquincy** [comment]
@OhBonsai  暂时还不支持哦，不过这是个很常用的场景，所以我会尽快支持这个功能，最晚这周末会发布，到时会在issue中通知你。感谢支持~

**Comment by chenquincy** [comment]
@OhBonsai  2.3.0版本已发布，使用方式：
``` js
{
  type: 'string',
  props: {
    type: 'areatext',
    rows: 3
  }
}
```
对应组件的属性都可以放在props中传入，组件属性可以查阅element-ui对应组件的属性

**Comment by OhBonsai** [comment]
哈哈， 谢谢陈兄～

**Comment by OhBonsai** [comment]
@chenquincy 好像我无法采用这种形式

```
{
    type: 'string',
    props: [
        {type: 'teaxarea', rows: 3}
   ]
}
```


![image](https://user-images.githubusercontent.com/18596879/65405895-4b8ebf00-de10-11e9-914c-84a2b77379af.png)

**Comment by chenquincy** [comment]
@OhBonsai  props属性的类型错误，直接使用对象即可
``` js
{
  type: 'string',
  props: {
    type: 'textarea',
    rows: 3
  }
}
```
你用的是数组

**Comment by OhBonsai** [comment]
Sorry... 我搞错了。  可能是看到你更新 脑子太兴奋。。 
不知道怎么就把更新多个属性 就直接想到  **一个属性是数组的一个元素**.....  

🙏🙏

**Comment by chenquincy** [comment]
@OhBonsai  hhhh，不用道歉的，出问题很正常，感谢支持。
