### ISSUE TITLE
Boolean type render with el-input 

### ISSUE THREAD

**Issue by OhBonsai** [chenquincy/vue-dynamic-form-component#7]
不知道是我姿势不对还是， 我看了下官网也是
![image](https://user-images.githubusercontent.com/18596879/65414763-e8f4ed80-de26-11e9-9dbc-605ab61ce9b7.png)

![image](https://user-images.githubusercontent.com/18596879/65414782-f611dc80-de26-11e9-8992-c61bffa02dec.png)

**Comment by chenquincy** [comment]
@OhBonsai 确认是个bug，我已经修复了，你更新到 2.3.1 版本即可
