### ISSUE TITLE
Fetching Data.

### ISSUE THREAD

**Issue by sebastianpmb** [chenquincy/vue-dynamic-form-component#8]
Hello,

How are you ?

Could you please post an examplo of how to fetch data to fill in the fields of the form ?

Thanks !

**Comment by chenquincy** [comment]
@sebastianpmb  You can call `this.$set` to update `data` of the form after fetch the data.
``` js
const data = await $ajax('xxxx') // fetch data
this.$set(this, 'data', data)
```
Then fields of the form will be auto fill with the new data. Close this issue if it work.

**Comment by chenquincy** [comment]
Reopen the issue if the problem not resolved.
