### ISSUE TITLE
enum options不支持动态数据

### ISSUE THREAD

**Issue by shangjunimo** [chenquincy/vue-dynamic-form-component#9]
enum options不支持动态数据

**Comment by chenquincy** [comment]
@shangjunimo  动态修改options需要用 `$set`

**Comment by chenquincy** [comment]
@shangjunimo  能否提供demo？通过 `this.descriptors.xxx.defaultField.options = newData` 是可以动态更改 options 的

**Comment by shangjunimo** [comment]
ok, ths
